name: "❓ Question"
description: "I want to ask a question."
labels: "question"
body:
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "⚠️ Research before questioning"
      description: |
        Before asking a question, make sure you have:
        - Searched existing questions [forum-EN](https://discuss.nebula-graph.io/) or [forum-CH](https://discuss.nebula-graph.com.cn/).
        - Googled your question.
        - Searched open and closed [GitHub issues](https://github.com/vesoft-inc/nebula/issues?q=is%3Aissue).
        - Read the [documentation-EN](https://docs.nebula-graph.io/) or [documentation-CH](https://docs.nebula-graph.com.cn/).
      options:
        - label: "I checked and didn't find similar questions/answers"
          required: true
  - type: textarea
    id: question
    validations:
      required: true
    attributes:
      label: "📝 Describe your question"
      description: "Describe what are you asking for..."
      placeholder: "..."
